import type { V3ModuleConfig, V3ModuleCounts, V3ModuleKey, V3ReviewRow, V3ReviewStatus } from './types'

const createCounts = (rows: V3ReviewRow[]): V3ModuleCounts => ({
  needs_review: rows.filter((row) => row.status === 'needs_review').length,
  ready_for_sync: rows.filter((row) => row.status === 'ready_for_sync').length,
  synced: rows.filter((row) => row.status === 'synced').length,
  excluded: rows.filter((row) => row.status === 'excluded').length,
})

export const REVIEW_TAB_LABELS: Record<V3ReviewStatus, string> = {
  needs_review: 'Needs review',
  ready_for_sync: 'Ready for sync',
  synced: 'Synced',
  excluded: 'Excluded',
}

export const REVIEW_STATUS_ORDER: V3ReviewStatus[] = [
  'needs_review',
  'ready_for_sync',
  'synced',
  'excluded',
]

export const REVIEW_ORDER: V3ModuleKey[] = ['items', 'vendors', 'bills', 'advances', 'expenses']

export const SYNC_STEP_LABELS = [
  'Preparing Ray-approved mappings',
  'Validating ledger selections',
  'Syncing entries into books',
  'Refreshing accounting status',
] as const

export const MODULE_CONFIG: Record<V3ModuleKey, V3ModuleConfig> = {
  items: {
    key: 'items',
    label: 'Items',
    route: '/v3/accounting/items',
    description: 'Review inventory intent, tally item mapping, and purchase accounts before sync.',
    sourceColumnLabel: 'RazorpayX item',
    targetColumnLabel: 'Purchase Account',
    secondaryTargetColumnLabel: 'Tally Item',
    supportsInventory: true,
  },
  vendors: {
    key: 'vendors',
    label: 'Vendors',
    route: '/v3/accounting/vendors',
    description: 'Confirm Ray vendor ledger matches before supplier bills move into books.',
    sourceColumnLabel: 'RazorpayX Vendor',
    targetColumnLabel: 'Tally Vendor Ledger',
  },
  bills: {
    key: 'bills',
    label: 'Bills',
    route: '/v3/accounting/bills',
    description: 'Approve bill postings, accounting dates, and target ledgers for the close window.',
    sourceColumnLabel: 'Vendor',
    targetColumnLabel: 'Tally Ledger',
    referenceColumnLabel: 'Bill',
  },
  expenses: {
    key: 'expenses',
    label: 'Expenses',
    route: '/v3/accounting/expenses',
    description: 'Review payout ledger mappings before expense postings are synced into books.',
    sourceColumnLabel: 'Vendor',
    targetColumnLabel: 'Tally Ledger',
    referenceColumnLabel: 'Bill',
  },
  advances: {
    key: 'advances',
    label: 'Advances',
    route: '/v3/accounting/advances',
    description: 'Resolve vendor advance ledgers so prepayments land in the right bucket.',
    sourceColumnLabel: 'Vendor',
    targetColumnLabel: 'Tally Ledger',
    referenceColumnLabel: 'Bill',
  },
  costCenters: {
    key: 'costCenters',
    label: 'Cost Centers',
    route: '/v3/accounting/more/cost-centers',
    description: 'Map internal cost centers to the correct book structure before sync.',
    sourceColumnLabel: 'RazorpayX Cost Center',
    targetColumnLabel: 'Tally Cost Center',
  },
  gst: {
    key: 'gst',
    label: 'GST',
    route: '/v3/accounting/more/gst',
    description: 'Review ledger mapping for GST treatment before indirect tax postings go live.',
    sourceColumnLabel: 'RazorpayX GST Label',
    targetColumnLabel: 'Tally Ledger',
  },
  tds: {
    key: 'tds',
    label: 'TDS',
    route: '/v3/accounting/more/tds',
    description: 'Keep TDS suggestions aligned to the right withholding ledger setup.',
    sourceColumnLabel: 'RazorpayX TDS Label',
    targetColumnLabel: 'Tally Ledger',
  },
}

export const PURCHASE_ACCOUNT_OPTIONS = [
  'Purchases @ 18%',
  'Engineering Expense',
  'Consulting Expense',
  'Marketing Expense',
  'Office Supplies Expense',
]

export const TALLY_ITEM_OPTIONS = [
  'IT Equipment Stock',
  'Peripherals Stock',
  'Electronics Stock',
  'Furniture Stock',
]

export const VENDOR_LEDGER_OPTIONS = [
  'Sundry Creditors',
  'Tech Services A/C',
  'Office Supplies A/C',
  'Raw Materials A/C',
  'Marketing Expense',
]

export const TALLY_LEDGER_OPTIONS = [
  'Purchases A/C',
  'IT Procurement A/C',
  'Vendor Advances A/C',
  'Payout Expense A/C',
  'Operations Expense A/C',
  'GST Input Credit',
  'TDS Payable 194J',
]

export const COST_CENTER_OPTIONS = ['Marketing Department', 'Operations Dept', 'Sales Division', 'Finance Dept']

export const GST_LEDGER_OPTIONS = ['Input CGST', 'Input SGST', 'Input IGST', 'GST Suspense Ledger']

export const TDS_LEDGER_OPTIONS = ['TDS Payable 194C', 'TDS Payable 194I', 'TDS Payable 194J']

export const INITIAL_MODULE_ROWS: Record<V3ModuleKey, V3ReviewRow[]> = {
  items: [
    {
      id: 'item_v3_001',
      sourceLabel: 'Laptop Dock',
      trackInventory: true,
      mappingState: 'ray',
      targetLabel: 'Purchases @ 18%',
      secondaryTargetLabel: 'IT Equipment Stock',
      status: 'needs_review',
      explanation: 'Ray matched the HSN cluster to IT peripherals already booked under Purchases @ 18%.',
    },
    {
      id: 'item_v3_002',
      sourceLabel: 'Conference Camera',
      trackInventory: false,
      mappingState: 'missing',
      targetLabel: '',
      secondaryTargetLabel: '',
      status: 'needs_review',
      explanation: 'No prior pattern exists for this item name, so Ray needs your purchase account decision.',
    },
    {
      id: 'item_v3_003',
      sourceLabel: 'Wireless Keyboard',
      trackInventory: true,
      mappingState: 'ray',
      targetLabel: 'Purchases @ 18%',
      secondaryTargetLabel: 'Peripherals Stock',
      status: 'ready_for_sync',
      explanation: 'This mapping was auto-approved from a high-confidence stock pattern.',
    },
    {
      id: 'item_v3_004',
      sourceLabel: 'Standing Desk',
      trackInventory: false,
      mappingState: 'edited',
      targetLabel: 'Office Supplies Expense',
      secondaryTargetLabel: '',
      status: 'synced',
      explanation: 'Edited manually in the last sync window and successfully posted.',
    },
    {
      id: 'item_v3_005',
      sourceLabel: 'Projector Mount',
      trackInventory: true,
      mappingState: 'missing',
      targetLabel: '',
      secondaryTargetLabel: '',
      status: 'excluded',
      explanation: 'This item was excluded because the vendor sent an incomplete line description.',
    },
  ],
  vendors: [
    {
      id: 'vendor_v3_001',
      sourceLabel: 'Delta Logistics',
      mappingState: 'ray',
      targetLabel: 'Sundry Creditors',
      status: 'needs_review',
      explanation: 'Ray found a strong supplier history but held it for review because the GSTIN changed this month.',
    },
    {
      id: 'vendor_v3_002',
      sourceLabel: 'Omega Consulting',
      mappingState: 'missing',
      targetLabel: '',
      status: 'needs_review',
      explanation: 'No confident vendor ledger match exists for this supplier name.',
    },
    {
      id: 'vendor_v3_003',
      sourceLabel: 'Nova Technologies',
      mappingState: 'ray',
      targetLabel: 'Tech Services A/C',
      status: 'ready_for_sync',
      explanation: 'Matched from repeated bookings under the same PAN and bank account.',
    },
    {
      id: 'vendor_v3_004',
      sourceLabel: 'Acme Supplies Pvt Ltd',
      mappingState: 'edited',
      targetLabel: 'Office Supplies A/C',
      status: 'synced',
      explanation: 'Previously approved and already synced into books.',
    },
    {
      id: 'vendor_v3_005',
      sourceLabel: 'Prime Vendors Ltd',
      mappingState: 'missing',
      targetLabel: '',
      status: 'excluded',
      explanation: 'Excluded until procurement confirms the legal entity name.',
    },
  ],
  bills: [
    // ── 3 AI-mapped rows (action: Confirm) ───────────────────────────────────
    {
      id: 'bill_v3_001',
      sourceLabel: 'Delta Logistics',
      mappingState: 'ray',
      targetLabel: 'Operations Expense A/C',
      accountingDate: '28 Mar 2026',
      amount: 86500,
      referenceLabel: 'BILL-2026-0148',
      status: 'needs_review',
      explanation: 'Ray kept this for review because the posting date falls inside the close freeze window.',
    },
    {
      id: 'bill_v3_002',
      sourceLabel: 'Meridian Freight Co.',
      mappingState: 'ray',
      targetLabel: 'Operations Expense A/C',
      accountingDate: '31 Mar 2026',
      amount: 74200,
      referenceLabel: 'BILL-2026-0168',
      status: 'needs_review',
      explanation: 'Ray matched to freight ledger but supplier has two active GSTINs — confirm before booking.',
    },
    {
      id: 'bill_v3_003',
      sourceLabel: 'BlueSky Cloud Services',
      mappingState: 'ray',
      targetLabel: 'IT Procurement A/C',
      accountingDate: '01 Apr 2026',
      amount: 54800,
      referenceLabel: 'BILL-2026-0177',
      status: 'needs_review',
      explanation: 'Recurring SaaS subscription — Ray pre-mapped but flagged due to a 12% GST rate change.',
    },
    // ── 10 manual-mapping rows (action: Map ledger) ───────────────────────────
    {
      id: 'bill_v3_004',
      sourceLabel: 'Omega Consulting',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '29 Mar 2026',
      amount: 142000,
      referenceLabel: 'BILL-2026-0151',
      status: 'needs_review',
      explanation: 'No reliable ledger match was found from description or prior books.',
    },
    {
      id: 'bill_v3_005',
      sourceLabel: 'Apex Interiors',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '01 Apr 2026',
      amount: 189000,
      referenceLabel: 'BILL-2026-0174',
      status: 'needs_review',
      explanation: 'First-time supplier — no prior ledger mapping found. Select an account to proceed.',
    },
    {
      id: 'bill_v3_006',
      sourceLabel: 'Pinnacle Events',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '02 Apr 2026',
      amount: 67300,
      referenceLabel: 'BILL-2026-0183',
      status: 'needs_review',
      explanation: 'Event management vendor — unclear cost category, needs manual classification.',
    },
    {
      id: 'bill_v3_007',
      sourceLabel: 'Cascade Printing',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '02 Apr 2026',
      amount: 18400,
      referenceLabel: 'BILL-2026-0185',
      status: 'needs_review',
      explanation: 'New vendor, no historical mapping. Select a ledger to continue.',
    },
    {
      id: 'bill_v3_008',
      sourceLabel: 'Vantage Legal LLP',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '03 Apr 2026',
      amount: 225000,
      referenceLabel: 'BILL-2026-0190',
      status: 'needs_review',
      explanation: 'Legal retainer — TDS treatment pending confirmation from finance.',
    },
    {
      id: 'bill_v3_009',
      sourceLabel: 'Swift Courier Services',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '03 Apr 2026',
      amount: 9800,
      referenceLabel: 'BILL-2026-0192',
      status: 'needs_review',
      explanation: 'Logistics bill with no matching vendor record — choose appropriate freight account.',
    },
    {
      id: 'bill_v3_010',
      sourceLabel: 'Horizon Architects',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '04 Apr 2026',
      amount: 410000,
      referenceLabel: 'BILL-2026-0197',
      status: 'needs_review',
      explanation: 'Capex vs. opex classification not determined — awaiting approval from controllership.',
    },
    {
      id: 'bill_v3_011',
      sourceLabel: 'SkyLink Telecom',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '04 Apr 2026',
      amount: 34600,
      referenceLabel: 'BILL-2026-0199',
      status: 'needs_review',
      explanation: 'Telecom bill with mixed usage — split between IT and admin not confirmed.',
    },
    {
      id: 'bill_v3_012',
      sourceLabel: 'GreenPath Sustainability',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '05 Apr 2026',
      amount: 52000,
      referenceLabel: 'BILL-2026-0204',
      status: 'needs_review',
      explanation: 'New CSR-linked vendor — no standard ledger for this expense category yet.',
    },
    {
      id: 'bill_v3_013',
      sourceLabel: 'Redwood Staffing',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '05 Apr 2026',
      amount: 178000,
      referenceLabel: 'BILL-2026-0207',
      status: 'needs_review',
      explanation: 'Contract staffing invoice — section 194C TDS applicability to be confirmed.',
    },
    // ── Ready for sync ────────────────────────────────────────────────────────
    {
      id: 'bill_v3_014',
      sourceLabel: 'Nova Technologies',
      mappingState: 'ray',
      targetLabel: 'IT Procurement A/C',
      accountingDate: '29 Mar 2026',
      amount: 216000,
      referenceLabel: 'BILL-2026-0156',
      status: 'ready_for_sync',
      explanation: 'Auto-approved based on repeated IT hardware purchases under the same vendor and amount range.',
    },
    {
      id: 'bill_v3_015',
      sourceLabel: 'Infra Build Ltd',
      mappingState: 'ray',
      targetLabel: 'Operations Expense A/C',
      accountingDate: '02 Apr 2026',
      amount: 312500,
      referenceLabel: 'BILL-2026-0182',
      status: 'ready_for_sync',
      explanation: 'Ray approved — consistent with prior civil work bookings under the same project code.',
    },
    // ── Synced ────────────────────────────────────────────────────────────────
    {
      id: 'bill_v3_016',
      sourceLabel: 'Acme Supplies Pvt Ltd',
      mappingState: 'edited',
      targetLabel: 'Purchases A/C',
      accountingDate: '26 Mar 2026',
      amount: 58000,
      referenceLabel: 'BILL-2026-0129',
      status: 'synced',
      explanation: 'Synced in the last run after manual ledger correction.',
    },
    {
      id: 'bill_v3_017',
      sourceLabel: 'Greenfield Catering',
      mappingState: 'edited',
      targetLabel: 'Purchases A/C',
      accountingDate: '27 Mar 2026',
      amount: 21600,
      referenceLabel: 'BILL-2026-0139',
      status: 'synced',
      explanation: 'Posted to books after ledger was manually corrected from meals to purchases.',
    },
    // ── Excluded ──────────────────────────────────────────────────────────────
    {
      id: 'bill_v3_018',
      sourceLabel: 'Sterling Supplies',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '30 Mar 2026',
      amount: 32500,
      referenceLabel: 'BILL-2026-0161',
      status: 'excluded',
      explanation: 'Excluded because the attached invoice is duplicated with a pending bill.',
    },
  ],
  expenses: [
    {
      id: 'expense_v3_001',
      sourceLabel: 'Airport Transfers',
      mappingState: 'ray',
      targetLabel: 'Payout Expense A/C',
      accountingDate: '28 Mar 2026',
      amount: 12300,
      referenceLabel: 'PAYOUT-2026-4102',
      status: 'needs_review',
      explanation: 'Ray suggests a payout expense ledger but flagged this because the narration mentions a client recharge.',
    },
    {
      id: 'expense_v3_002',
      sourceLabel: 'Field Operations',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '29 Mar 2026',
      amount: 48600,
      referenceLabel: 'PAYOUT-2026-4117',
      status: 'needs_review',
      explanation: 'The payout memo did not match any existing expense pattern strongly enough for auto-booking.',
    },
    {
      id: 'expense_v3_003',
      sourceLabel: 'Merchant Refund Buffer',
      mappingState: 'ray',
      targetLabel: 'Operations Expense A/C',
      accountingDate: '30 Mar 2026',
      amount: 91500,
      referenceLabel: 'PAYOUT-2026-4142',
      status: 'ready_for_sync',
      explanation: 'Repeated payout mapping was approved automatically by Ray.',
    },
    {
      id: 'expense_v3_004',
      sourceLabel: 'Partner Reimbursement',
      mappingState: 'edited',
      targetLabel: 'Payout Expense A/C',
      accountingDate: '25 Mar 2026',
      amount: 27800,
      referenceLabel: 'PAYOUT-2026-4022',
      status: 'synced',
      explanation: 'Manually mapped and synced in the previous close cycle.',
    },
    {
      id: 'expense_v3_005',
      sourceLabel: 'Travel Escrow',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '26 Mar 2026',
      amount: 18000,
      referenceLabel: 'PAYOUT-2026-4055',
      status: 'excluded',
      explanation: 'Excluded because the payout is being reversed by treasury.',
    },
  ],
  advances: [
    {
      id: 'advance_v3_001',
      sourceLabel: 'Delta Logistics',
      mappingState: 'ray',
      targetLabel: 'Vendor Advances A/C',
      accountingDate: '27 Mar 2026',
      amount: 120000,
      referenceLabel: 'ADV-2026-0094',
      status: 'needs_review',
      explanation: 'Ray identified this as a vendor advance from payment terms and invoice absence.',
    },
    {
      id: 'advance_v3_002',
      sourceLabel: 'Prime Vendors Ltd',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '28 Mar 2026',
      amount: 76000,
      referenceLabel: 'ADV-2026-0101',
      status: 'needs_review',
      explanation: 'There is not enough history to decide whether this should be an advance or direct expense.',
    },
    {
      id: 'advance_v3_003',
      sourceLabel: 'Nova Technologies',
      mappingState: 'ray',
      targetLabel: 'Vendor Advances A/C',
      accountingDate: '29 Mar 2026',
      amount: 54000,
      referenceLabel: 'ADV-2026-0110',
      status: 'ready_for_sync',
      explanation: 'Approved automatically from contract-based advance patterns.',
    },
    {
      id: 'advance_v3_004',
      sourceLabel: 'Alpha Resources',
      mappingState: 'edited',
      targetLabel: 'Vendor Advances A/C',
      accountingDate: '22 Mar 2026',
      amount: 61000,
      referenceLabel: 'ADV-2026-0076',
      status: 'synced',
      explanation: 'Synced last week after confirming this payment was a milestone advance.',
    },
    {
      id: 'advance_v3_005',
      sourceLabel: 'Omega Consulting',
      mappingState: 'missing',
      targetLabel: '',
      accountingDate: '23 Mar 2026',
      amount: 25000,
      referenceLabel: 'ADV-2026-0079',
      status: 'excluded',
      explanation: 'Excluded until the vendor shares the supporting contract note.',
    },
  ],
  costCenters: [
    {
      id: 'cc_v3_001',
      sourceLabel: 'Marketing West',
      mappingState: 'ray',
      targetLabel: 'Marketing Department',
      status: 'needs_review',
      explanation: 'Mapped from branch naming and prior tagged payouts.',
    },
    {
      id: 'cc_v3_002',
      sourceLabel: 'Sales Pods',
      mappingState: 'ray',
      targetLabel: 'Sales Division',
      status: 'ready_for_sync',
      explanation: 'Auto-approved because the team code matches the existing cost center tree.',
    },
    {
      id: 'cc_v3_003',
      sourceLabel: 'Core Ops',
      mappingState: 'edited',
      targetLabel: 'Operations Dept',
      status: 'synced',
      explanation: 'Already synced after finance re-labeled the cost center last week.',
    },
    {
      id: 'cc_v3_004',
      sourceLabel: 'Board Projects',
      mappingState: 'missing',
      targetLabel: '',
      status: 'excluded',
      explanation: 'Excluded pending cost center approval from controllership.',
    },
  ],
  gst: [
    {
      id: 'gst_v3_001',
      sourceLabel: 'Input GST 18%',
      mappingState: 'ray',
      targetLabel: 'Input IGST',
      status: 'needs_review',
      explanation: 'Held for review because the supplier state code is inconsistent across recent bills.',
    },
    {
      id: 'gst_v3_002',
      sourceLabel: 'Input GST 12%',
      mappingState: 'ray',
      targetLabel: 'Input CGST',
      status: 'ready_for_sync',
      explanation: 'Ray reused the approved tax mapping from your last two close cycles.',
    },
    {
      id: 'gst_v3_003',
      sourceLabel: 'GST Reversal',
      mappingState: 'edited',
      targetLabel: 'GST Suspense Ledger',
      status: 'synced',
      explanation: 'Finance manually approved this suspense ledger mapping earlier this month.',
    },
    {
      id: 'gst_v3_004',
      sourceLabel: 'Reverse Charge GST',
      mappingState: 'missing',
      targetLabel: '',
      status: 'excluded',
      explanation: 'Excluded until the reverse-charge treatment is confirmed by tax.',
    },
  ],
  tds: [
    {
      id: 'tds_v3_001',
      sourceLabel: 'Professional Fees',
      mappingState: 'ray',
      targetLabel: 'TDS Payable 194J',
      status: 'needs_review',
      explanation: 'Ray suggests 194J based on the invoice description and prior withholding decisions.',
    },
    {
      id: 'tds_v3_002',
      sourceLabel: 'Office Rent',
      mappingState: 'ray',
      targetLabel: 'TDS Payable 194I',
      status: 'ready_for_sync',
      explanation: 'Repeated rent pattern auto-approved from the landlord vendor history.',
    },
    {
      id: 'tds_v3_003',
      sourceLabel: 'Contract Labor',
      mappingState: 'edited',
      targetLabel: 'TDS Payable 194C',
      status: 'synced',
      explanation: 'This withholding mapping was approved and synced yesterday.',
    },
    {
      id: 'tds_v3_004',
      sourceLabel: 'Director Sitting Fees',
      mappingState: 'missing',
      targetLabel: '',
      status: 'excluded',
      explanation: 'Excluded until payroll confirms the treatment is outside this sync cycle.',
    },
  ],
}

export const MODULE_NAV_COUNTS = Object.fromEntries(
  Object.entries(INITIAL_MODULE_ROWS).map(([key, rows]) => [key, createCounts(rows)]),
) as Record<V3ModuleKey, V3ModuleCounts>

export const getModuleCounts = (rows: V3ReviewRow[]): V3ModuleCounts => createCounts(rows)
